
name: 'SaaS_Subscription_and_Churn_Analytics'
version: '1.0.0'

profile: 'SaaS_Subscription_and_Churn_Analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Default model configs
models:
  SaaS_Subscription_and_Churn_Analytics:
    # Staging / Bronze layer defaults
    bronze:
      +materialized: table
      +schema: bronze

    # Intermediate / Silver layer defaults
    silver:
      +materialized: view
      +schema: silver

    # Mart / Gold layer defaults
    gold:
      +materialized: table
      +schema: gold
